[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
chiliz_testnet = "https://spicy-rpc.chiliz.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
